# Generated by Django 4.0.1 on 2022-01-09 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255, verbose_name='Identifier')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('category', models.CharField(max_length=255, verbose_name='Category')),
                ('unit', models.CharField(max_length=255, verbose_name='Unit')),
                ('procurement_type', models.CharField(max_length=255, verbose_name='Procurement type')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
            ],
        ),
        migrations.CreateModel(
            name='Assembly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('quantity', models.DecimalField(decimal_places=3, default=0.0, max_digits=8, verbose_name='Quantity')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bom.component')),
            ],
            options={
                'verbose_name': 'Assembly',
                'verbose_name_plural': 'Assemblies',
            },
        ),
    ]
